name: First Interaction

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Hey, thanks for opening your first issue! 🙂 \nBe sure to check out [the contribution guidelines](https://github.com/thomasbnt/Night_Pihole/blob/master/CONTRIBUTING.md). Thanks!"
        pr-message: "Hey, congratulations on your first pull request for Night_PiHole !"
